# Generated by Django 3.2.3 on 2021-06-13 20:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('identitynumber', models.CharField(max_length=200)),
                ('sex', models.CharField(default='x', max_length=1)),
                ('date_of_birth', models.DateTimeField(verbose_name='date of birth')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'animals',
            },
        ),
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField()),
                ('date_recorded', models.DateTimeField(default=datetime.datetime(2021, 6, 14, 6, 59, 45, 556622), verbose_name='date recorded')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ahtracker.animal')),
            ],
            options={
                'verbose_name_plural': 'weights',
            },
        ),
    ]
