# Generated by Django 3.2.3 on 2021-06-13 21:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahtracker', '0002_alter_weight_date_recorded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weight',
            name='date_recorded',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 14, 7, 30, 42, 258823), verbose_name='date recorded'),
        ),
    ]
