# Generated by Django 3.2.3 on 2021-06-13 22:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahtracker', '0004_alter_weight_date_recorded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weight',
            name='date_recorded',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 14, 8, 20, 58, 845324), verbose_name='date recorded'),
        ),
    ]
