# Generated by Django 3.2.3 on 2021-06-13 22:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahtracker', '0005_alter_weight_date_recorded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weight',
            name='date_recorded',
            field=models.DateTimeField(default=datetime.datetime.now(), verbose_name='date recorded'),
        ),
    ]
